let exams=[];
const $=id=>document.getElementById(id); const today=()=>{let d=new Date();d.setHours(0,0,0,0);return d};
const days=e=>e.date===null?null:Math.ceil((new Date(e.date+'T00:00:00')-today())/86400000);
const left=e=>{let d=days(e);return d===null?'Date TBA':d<0?'Completed':d===0?'Today':`${d.toLocaleString()} days left`};
const savedIds=()=>JSON.parse(localStorage.getItem('examtrack_saved')||'[]');
function toggleSave(id){let a=savedIds();a=a.includes(id)?a.filter(x=>x!==id):[...a,id];localStorage.setItem('examtrack_saved',JSON.stringify(a));render();renderSaved()}
function card(e){let d=days(e),saved=savedIds().includes(e.id);return `<article class="card"><div class="cardTop"><span class="tag ${e.cat}">${e.cat.toUpperCase()}</span><button class="star ${saved?'on':''}" onclick="toggleSave('${e.id}')">★</button></div><h3>${e.name}</h3><p class="org">${e.org}</p><div class="date">${e.display}</div><div class="count ${d===null?'tba':''}">${left(e)}</div>${e.applyLabel?`<div class="deadline">${e.apply?`Application deadline: ${new Date(e.apply+'T00:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})} · `:''}${e.applyLabel}</div>`:''}<div class="cardBottom"><button onclick="openExam('${e.id}')">View details</button><a href="${e.source}" target="_blank" rel="noopener">Official ↗</a></div></article>`}
function render(){let q=$('search').value.toLowerCase(),cat=$('cat').value,sort=$('sort').value,f=document.querySelector('.chip.active').dataset.filter;let a=exams.filter(e=>(cat==='all'||e.cat===cat)&&(f==='all'||e.cat===f)&&`${e.name} ${e.org} ${e.cat}`.toLowerCase().includes(q));a.sort((x,y)=>sort==='name'?x.name.localeCompare(y.name):(x.date||'9999').localeCompare(y.date||'9999'));$('examGrid').innerHTML=a.map(card).join('')||'<div class="empty">No exams match your search.</div>';stats();next()}
function stats(){let up=exams.filter(e=>days(e)>=0).length,saved=savedIds().length;$('stats').innerHTML=`<div><b>${up}</b><span>confirmed upcoming</span></div><div><b>${exams.length}</b><span>tracked exams</span></div><div><b>${saved}</b><span>saved for you</span></div><div><b>Auto</b><span>source monitoring</span></div>`}
function next(){let a=exams.filter(e=>e.date&&days(e)>=0).sort((a,b)=>new Date(a.date)-new Date(b.date))[0];if(!a){$('nextName').textContent='No dated exams';return}$('nextName').textContent=a.name;$('nextDays').textContent=left(a);$('nextDate').textContent=a.display}
function openExam(id){let e=exams.find(x=>x.id===id);$('modalBody').innerHTML=`<p class="eyebrow">${e.cat.toUpperCase()}</p><h2>${e.name}</h2><p>${e.org}</p><div class="modalGrid"><div><small>EXAM DATE</small><strong>${e.display}</strong><span>${left(e)}</span></div><div><small>APPLICATION</small><strong>${e.applyLabel||'TBA'}</strong></div></div><h3>Syllabus</h3><div class="topics">${e.syllabus.map(x=>`<div class="topic"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}</div><a class="btn" href="${e.source}" target="_blank">Open official source ↗</a>`;$('modal').classList.remove('hidden')}
function renderSyllabus(id='gate27'){let e=exams.find(x=>x.id===id);if(!e)return;$('syllabusPanel').innerHTML=`<div class="syHead"><div><p class="eyebrow">${e.org}</p><h3>${e.name}</h3></div><span>${left(e)}</span></div><div class="topics">${e.syllabus.map(x=>`<div class="topic"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}</div><a href="${e.source}" target="_blank" class="sourceLink">Open official source ↗</a>`}
function renderTimeline(){let months={};exams.filter(e=>e.date).forEach(e=>{let k=e.date.slice(0,7);(months[k]??=[]).push(e)});$('timeline').innerHTML=Object.entries(months).sort().map(([m,arr])=>`<div class="month"><h3>${new Date(m+'-01').toLocaleDateString('en-IN',{month:'long',year:'numeric'})}</h3>${arr.map(e=>`<button onclick="openExam('${e.id}')"><span>${e.display}</span><strong>${e.name}</strong><em>${left(e)}</em></button>`).join('')}</div>`).join('')||'<div class="empty">No confirmed dates yet.</div>'}
function renderSaved(){let a=exams.filter(e=>savedIds().includes(e.id));$('saved').innerHTML=a.length?a.map(card).join(''):'<div class="empty">No saved exams yet. Hit ★ on an exam card.</div>'}
async function boot(){try{let r=await fetch('exams.json?ts='+Date.now());let data=await r.json();exams=data.exams||[];$('lastChecked').textContent=`Sources checked: ${data.last_checked||'—'}`;$('syllabusSelect').innerHTML=exams.map(e=>`<option value="${e.id}">${e.name}</option>`).join('');$('syllabusSelect').value='gate27';$('syllabusSelect').onchange=e=>renderSyllabus(e.target.value);render();renderTimeline();renderSyllabus();renderSaved();}catch(err){$('examGrid').innerHTML='<div class="empty">Could not load exam data. Check the data file or network connection.</div>';console.error(err)}}
$('search').oninput=render;$('cat').onchange=render;$('sort').onchange=render;$('myOnly').onclick=()=>{$('search').value='';$('cat').value='all';document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));document.querySelector('[data-filter="all"]').classList.add('active');let a=exams.filter(e=>savedIds().includes(e.id));$('examGrid').innerHTML=a.length?a.map(card).join(''):'<div class="empty">No saved exams yet.</div>'};document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()});$('close').onclick=()=>$('modal').classList.add('hidden');$('modal').onclick=e=>{if(e.target.id==='modal')$('modal').classList.add('hidden')};$('theme').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('theme',document.body.classList.contains('light')?'light':'dark')};if(localStorage.getItem('theme')==='light')document.body.classList.add('light');boot();setInterval(()=>{render();renderSaved()},60000);
